# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDateTime', models.DateTimeField(blank=True, null=True, verbose_name='\u8d77\u59cb\u65f6\u95f4')),
                ('endDateTime', models.DateTimeField(blank=True, null=True, verbose_name='\u7ed3\u675f\u65f6\u95f4')),
                ('visibility', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u53ef\u89c1\u6027')),
            ],
            options={
                'verbose_name': '\u6d3b\u52a8',
                'verbose_name_plural': '\u6d3b\u52a8',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5730\u57401')),
                ('address2', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5730\u57402')),
                ('address3', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5730\u57403')),
                ('address4', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5730\u57404')),
                ('phone1', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u7535\u8bdd1')),
                ('contact1', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u8054\u7cfb\u4eba1')),
                ('phone2', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u7535\u8bdd2')),
                ('contact2', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u8054\u7cfb\u4eba2')),
            ],
            options={
                'verbose_name': '\u5730\u5740',
                'verbose_name_plural': '\u5730\u5740',
            },
        ),
        migrations.CreateModel(
            name='AddressType',
            fields=[
                ('key', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='\u4e3b\u952e')),
                ('description', models.CharField(max_length=255, verbose_name='\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u5730\u5740\u7c7b\u578b',
                'verbose_name_plural': '\u5730\u5740\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='AppNavAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u7c7b\u578b')),
                ('pageApp', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5e94\u7528')),
                ('pageAction', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u52a8\u4f5c')),
                ('pageParams', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u53c2\u6570')),
                ('pageMode', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u6a21\u5f0f')),
                ('accessedAt', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u4e8e')),
            ],
            options={
                'verbose_name': '\u5e94\u7528\u8bbf\u95ee\u65e5\u5fd7',
                'verbose_name_plural': '\u5e94\u7528\u8bbf\u95ee\u65e5\u5fd7',
            },
        ),
        migrations.CreateModel(
            name='AuthObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.BooleanField(default=False, verbose_name='\u53ef\u521b\u5efa')),
                ('read', models.BooleanField(default=False, verbose_name='\u53ef\u67e5\u770b')),
                ('update', models.BooleanField(default=False, verbose_name='\u53ef\u66f4\u65b0')),
                ('delete', models.BooleanField(default=False, verbose_name='\u53ef\u5220\u9664')),
            ],
            options={
                'verbose_name': '\u6743\u9650\u5bf9\u8c61',
                'verbose_name_plural': '\u6743\u9650\u5bf9\u8c61',
            },
        ),
        migrations.CreateModel(
            name='AuthObjectType',
            fields=[
                ('key', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='\u4e3b\u952e')),
                ('description', models.CharField(max_length=255, verbose_name='\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u6743\u9650\u5bf9\u8c61\u7c7b\u578b',
                'verbose_name_plural': '\u6743\u9650\u5bf9\u8c61\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='BP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnerNo', models.IntegerField(blank=True, null=True, verbose_name='\u4f19\u4f34\u7f16\u53f7')),
                ('firstName', models.CharField(blank=True, max_length=50, verbose_name='\u540d')),
                ('middleName', models.CharField(blank=True, max_length=50, verbose_name='\u4e2d\u95f4\u540d')),
                ('lastName', models.CharField(blank=True, max_length=50, verbose_name='\u59d3')),
                ('name1', models.CharField(blank=True, max_length=255, verbose_name='\u540d\u79f01')),
                ('name2', models.CharField(blank=True, max_length=255, verbose_name='\u540d\u79f02')),
                ('name3', models.CharField(blank=True, max_length=255, verbose_name='\u540d\u79f03')),
                ('name4', models.CharField(blank=True, max_length=255, verbose_name='\u540d\u79f04')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5934\u8854')),
                ('mobile', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u8054\u7cfb\u624b\u673a')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u8054\u7cfb\u90ae\u7bb1')),
                ('valid', models.BooleanField(default=True, verbose_name='\u6709\u6548\u6027')),
                ('deleteFlag', models.BooleanField(default=False, verbose_name='\u5220\u9664\u6807\u8bb0')),
                ('address1', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asAddress1Bp', to='crm.Address', verbose_name='\u5730\u57401')),
                ('address2', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asAddress2Bp', to='crm.Address', verbose_name='\u5730\u57402')),
            ],
            options={
                'verbose_name': '\u5546\u4e1a\u4f19\u4f34',
                'verbose_name_plural': '\u5546\u4e1a\u4f19\u4f34',
            },
        ),
        migrations.CreateModel(
            name='BPBaseType',
            fields=[
                ('key', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='\u4e3b\u952e')),
                ('description', models.CharField(max_length=255, verbose_name='\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u5546\u4e1a\u4f19\u4f34\u57fa\u672c\u7c7b\u578b\u5b9a\u4e49',
                'verbose_name_plural': '\u5546\u4e1a\u4f19\u4f34\u57fa\u672c\u7c7b\u578b\u5b9a\u4e49',
            },
        ),
        migrations.CreateModel(
            name='BPBEDef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessEntity', models.CharField(max_length=20, verbose_name='\u4f19\u4f34\u4e1a\u52a1\u5b9e\u4f53')),
            ],
            options={
                'verbose_name': '\u5546\u4e1a\u4f19\u4f34\u5b9e\u4f53\u5b9a\u4e49\u8868',
                'verbose_name_plural': '\u5546\u4e1a\u4f19\u4f34\u5b9e\u4f53\u5b9a\u4e49\u8868',
            },
        ),
        migrations.CreateModel(
            name='BPCustomized',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boolAttribute1', models.BooleanField(default=False, verbose_name='\u662f\u5426\u89e6\u8fbe')),
                ('boolAttribute2', models.BooleanField(default=False, verbose_name='\u662f\u5426\u7b7e\u7ea6')),
                ('boolAttribute3', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5bf9\u63a5')),
                ('legalPerson', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u6cd5\u4eba')),
                ('actualPerson', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5b9e\u9645\u63a7\u5236\u4eba')),
                ('corpStructure', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u7ec4\u7ec7\u7ed3\u6784')),
                ('corpLiscense', models.ImageField(blank=True, null=True, upload_to=b'bpAttachments', verbose_name='\u8425\u4e1a\u6267\u7167\u9644\u4ef6')),
                ('file1', models.FileField(blank=True, null=True, upload_to=b'bpAttachments', verbose_name='\u9644\u4ef61')),
                ('file2', models.FileField(blank=True, null=True, upload_to=b'bpAttachments', verbose_name='\u9644\u4ef62')),
                ('imgFile1', models.ImageField(blank=True, null=True, upload_to=b'bpAttachments', verbose_name='\u56fe\u72471')),
                ('imgFile2', models.ImageField(blank=True, null=True, upload_to=b'bpAttachments', verbose_name='\u56fe\u72472')),
                ('bp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crm.BP', verbose_name='\u4f19\u4f34\u5bf9\u8c61')),
                ('empResp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corpEmpResp', to='crm.BP', verbose_name='\u8d1f\u8d23\u4eba')),
            ],
            options={
                'verbose_name': '\u5546\u4e1a\u4f19\u4f34\u6269\u5c55\u8868',
                'verbose_name_plural': '\u5546\u4e1a\u4f19\u4f34\u6269\u5c55\u8868',
            },
        ),
        migrations.CreateModel(
            name='BPFieldDef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldKey', models.CharField(max_length=50, verbose_name='\u5b57\u6bb5\u4e3b\u952e')),
                ('attributeType', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u5b57\u6bb5\u5c5e\u6027')),
                ('valueType', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u503c\u7c7b\u578b')),
                ('storeType', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5b58\u50a8\u7c7b\u578b')),
                ('storeColumn', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5b58\u50a8\u5b57\u6bb5')),
                ('storeKey', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5b58\u50a8\u952e\u503c')),
            ],
            options={
                'verbose_name': '\u5546\u4e1a\u4f19\u4f34\u5b57\u6bb5\u5b9a\u4e49\u8868',
                'verbose_name_plural': '\u5546\u4e1a\u4f19\u4f34\u5b57\u6bb5\u5b9a\u4e49\u8868',
            },
        ),
        migrations.CreateModel(
            name='BPFileAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u79f0')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u63cf\u8ff0')),
                ('actualfilename', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5b9e\u9645\u6587\u4ef6\u540d')),
                ('file', models.FileField(blank=True, null=True, upload_to=b'bpAttachments', verbose_name='\u6587\u4ef6')),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'bpAttachments', verbose_name='\u56fe\u7247')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u4e8e')),
                ('deleteFlag', models.BooleanField(default=False, verbose_name='\u5220\u9664\u6807\u8bb0')),
                ('bp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.BP', verbose_name='\u5546\u4e1a\u4f19\u4f34')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bpFileCreator', to='crm.BP', verbose_name='\u521b\u5efa\u8005')),
            ],
            options={
                'verbose_name': '\u5546\u4e1a\u4f19\u4f34\u6587\u4ef6\u9644\u4ef6',
                'verbose_name_plural': '\u5546\u4e1a\u4f19\u4f34\u6587\u4ef6\u9644\u4ef6',
            },
        ),
        migrations.CreateModel(
            name='BPRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5907\u6ce8')),
                ('valid', models.BooleanField(default=True, verbose_name='\u6709\u6548\u6027')),
                ('bpA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asBPA', to='crm.BP', verbose_name='\u4f19\u4f34A')),
                ('bpB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asBPB', to='crm.BP', verbose_name='\u4f19\u4f34B')),
            ],
            options={
                'verbose_name': '\u5546\u4e1a\u4f19\u4f34\u5173\u7cfb',
                'verbose_name_plural': '\u5546\u4e1a\u4f19\u4f34\u5173\u7cfb',
            },
        ),
        migrations.CreateModel(
            name='BPRelType',
            fields=[
                ('key', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='\u4e3b\u952e')),
                ('description', models.CharField(max_length=255, verbose_name='\u63cf\u8ff0')),
                ('descAtoB', models.CharField(blank=True, max_length=255, null=True, verbose_name='A\u5bf9B\u5173\u7cfb\u540d\u79f0')),
                ('descBtoA', models.CharField(blank=True, max_length=255, null=True, verbose_name='B\u5bf9A\u5173\u7cfb\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u5546\u4e1a\u4f19\u4f34\u5173\u7cfb\u7c7b\u578b',
                'verbose_name_plural': '\u5546\u4e1a\u4f19\u4f34\u5173\u7cfb\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='BPStdViewLayoutConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.BooleanField(verbose_name='\u662f\u5426\u53ef\u89c1')),
                ('required', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5fc5\u987b')),
                ('editable', models.BooleanField(default=True, verbose_name='\u53ef\u5426\u7f16\u8f91')),
                ('labelPhraseId', models.CharField(max_length=20, verbose_name='\u6807\u7b7e\u77ed\u8bed\u4e3b\u952e')),
                ('appId', models.CharField(max_length=20, verbose_name='\u77ed\u8bed\u5e94\u7528\u4e3b\u952e')),
                ('locRow', models.IntegerField(verbose_name='\u6240\u5728\u884c')),
                ('locCol', models.IntegerField(verbose_name='\u6240\u5728\u5217')),
                ('locWidth', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u5bbd\u5ea6')),
                ('locHeight', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u9ad8\u5ea6')),
                ('valid', models.BooleanField(default=True, verbose_name='\u6709\u6548\u6027')),
            ],
            options={
                'verbose_name': '\u5546\u4e1a\u4f19\u4f34\u6807\u51c6\u89c6\u56fe\u914d\u7f6e\u8868',
                'verbose_name_plural': '\u5546\u4e1a\u4f19\u4f34\u6807\u51c6\u89c6\u56fe\u914d\u7f6e\u8868',
            },
        ),
        migrations.CreateModel(
            name='BPText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u4e8e')),
                ('content', models.TextField(blank=True, null=True, verbose_name='\u5185\u5bb9')),
                ('bp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.BP', verbose_name='\u4f19\u4f34')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bpTextCreator', to='crm.BP', verbose_name='\u521b\u5efa\u8005')),
            ],
            options={
                'verbose_name': '\u5546\u4e1a\u4f19\u4f34\u6587\u672c\u8868',
                'verbose_name_plural': '\u5546\u4e1a\u4f19\u4f34\u6587\u672c\u8868',
            },
        ),
        migrations.CreateModel(
            name='BPTextType',
            fields=[
                ('key', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='\u4e3b\u952e')),
                ('description', models.CharField(max_length=255, verbose_name='\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u5546\u4e1a\u4f19\u4f34\u6587\u672c\u7c7b\u578b\u5b9a\u4e49',
                'verbose_name_plural': '\u5546\u4e1a\u4f19\u4f34\u6587\u672c\u7c7b\u578b\u5b9a\u4e49',
            },
        ),
        migrations.CreateModel(
            name='BPType',
            fields=[
                ('key', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='\u4e3b\u952e')),
                ('description', models.CharField(max_length=255, verbose_name='\u63cf\u8ff0')),
                ('assignmentBlock', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u6269\u5c55\u6846')),
                ('baseType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.BPBaseType', verbose_name='\u57fa\u672c\u7c7b\u578b')),
            ],
            options={
                'verbose_name': '\u5546\u4e1a\u4f19\u4f34\u7c7b\u578b',
                'verbose_name_plural': '\u5546\u4e1a\u4f19\u4f34\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='ChangeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectId', models.IntegerField(verbose_name='\u5b9e\u4f53\u7f16\u53f7')),
                ('type', models.CharField(max_length=50, verbose_name='\u5b9e\u4f53\u7c7b\u578b')),
                ('objectField', models.CharField(max_length=50, verbose_name='\u5b9e\u4f53\u5b57\u6bb5')),
                ('oldValue', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5b57\u6bb5\u65e7\u503c')),
                ('oldKeyValue', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5b57\u6bb5\u65e7\u952e\u503c')),
                ('newValue', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5b57\u6bb5\u65b0\u503c')),
                ('newKeyValue', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5b57\u6bb5\u65b0\u952e\u503c')),
                ('updatedBy', models.CharField(max_length=255, verbose_name='\u66f4\u65b0\u8005')),
                ('updatedAt', models.DateTimeField(verbose_name='\u66f4\u65b0\u4e8e')),
            ],
            options={
                'verbose_name': '\u4fee\u6539\u5386\u53f2\u8bb0\u5f55\u8868',
                'verbose_name_plural': '\u4fee\u6539\u5386\u53f2\u8bb0\u5f55\u8868',
            },
        ),
        migrations.CreateModel(
            name='DistrictType',
            fields=[
                ('key', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='\u4e3b\u952e')),
                ('description', models.CharField(max_length=255, verbose_name='\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u5730\u533a\u7c7b\u578b',
                'verbose_name_plural': '\u5730\u533a\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='FieldType',
            fields=[
                ('key', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='\u4e3b\u952e')),
                ('description', models.CharField(max_length=255, verbose_name='\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u5b57\u6bb5\u7c7b\u578b\u8868',
                'verbose_name_plural': '\u5b57\u6bb5\u7c7b\u578b\u8868',
            },
        ),
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u79f0')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u63cf\u8ff0')),
                ('version', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7248\u672c')),
                ('actualfilename', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5b9e\u9645\u6587\u4ef6\u540d')),
                ('file', models.FileField(upload_to=b'attachments', verbose_name='\u6587\u4ef6')),
                ('deleteFlag', models.BooleanField(default=False, verbose_name='\u5220\u9664\u6807\u8bb0')),
            ],
            options={
                'verbose_name': '\u6587\u4ef6\u9644\u4ef6',
                'verbose_name_plural': '\u6587\u4ef6\u9644\u4ef6',
            },
        ),
        migrations.CreateModel(
            name='LockTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectId', models.IntegerField(verbose_name='\u5b9e\u4f53\u7f16\u53f7')),
                ('tableType', models.CharField(max_length=50, verbose_name='\u8868\u7c7b\u578b')),
                ('lockedBy', models.CharField(max_length=255, verbose_name='\u52a0\u9501\u8005')),
                ('lockedAt', models.DateTimeField(auto_now=True, verbose_name='\u52a0\u9501\u4e8e')),
            ],
            options={
                'verbose_name': '\u5b9e\u4f53\u9501\u5b9a\u8868',
                'verbose_name_plural': '\u5b9e\u4f53\u9501\u5b9a\u8868',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, verbose_name='\u63cf\u8ff0')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u4e8e')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u4e8e')),
                ('deleteFlag', models.BooleanField(default=False, verbose_name='\u5220\u9664\u6807\u8bb0')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='crm.BP', verbose_name='\u521b\u5efa\u8005')),
            ],
            options={
                'verbose_name': '\u5355\u636e\u8868',
                'verbose_name_plural': '\u5355\u636e\u8868',
            },
        ),
        migrations.CreateModel(
            name='OrderBaseType',
            fields=[
                ('key', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='\u4e3b\u952e')),
                ('description', models.CharField(max_length=255, verbose_name='\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u5355\u636e\u57fa\u672c\u7c7b\u578b\u5b9a\u4e49',
                'verbose_name_plural': '\u5355\u636e\u57fa\u672c\u7c7b\u578b\u5b9a\u4e49',
            },
        ),
        migrations.CreateModel(
            name='OrderBEDef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessEntity', models.CharField(max_length=20, verbose_name='\u5355\u636e\u4e1a\u52a1\u5b9e\u4f53')),
            ],
            options={
                'verbose_name': '\u5355\u636e\u5b9e\u4f53\u5b9a\u4e49\u8868',
                'verbose_name_plural': '\u5355\u636e\u5b9e\u4f53\u5b9a\u4e49\u8868',
            },
        ),
        migrations.CreateModel(
            name='OrderCustomized',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travelAmount', models.IntegerField(blank=True, null=True, verbose_name='\u5dee\u65c5\u91cf')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='\u989d\u5ea6')),
                ('stage', models.CharField(blank=True, max_length=5, null=True, verbose_name='\u9636\u6bb5')),
                ('goLiveDate', models.DateField(blank=True, null=True, verbose_name='\u4e0a\u7ebf\u65e5\u671f')),
                ('customerType', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u7ed3\u7b97\u7c7b\u578b')),
                ('tmcExtraFieldsChk', models.BooleanField(default=False)),
                ('connectionVia', models.CharField(blank=True, max_length=255, null=True)),
                ('uploadTimeFreq', models.CharField(blank=True, max_length=255, null=True)),
                ('uatpRatio', models.CharField(blank=True, max_length=255, null=True)),
                ('tmcResEmp', models.CharField(blank=True, max_length=255, null=True)),
                ('settleType', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u8d26\u6237\u7c7b\u578b')),
                ('file1', models.FileField(blank=True, null=True, upload_to=b'attachments', verbose_name='\u9644\u4ef61')),
                ('file2', models.FileField(blank=True, null=True, upload_to=b'attachments', verbose_name='\u9644\u4ef62')),
                ('imgFile1', models.ImageField(blank=True, null=True, upload_to=b'attachments', verbose_name='\u56fe\u72471')),
                ('imgFile2', models.ImageField(blank=True, null=True, upload_to=b'attachments', verbose_name='\u56fe\u72472')),
                ('checkResult', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5ba1\u6838\u7ed3\u679c')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crm.Order', verbose_name='\u5355\u636e')),
            ],
            options={
                'verbose_name': '\u5355\u636e\u6269\u5c55\u8868',
                'verbose_name_plural': '\u5355\u636e\u6269\u5c55\u8868',
            },
        ),
        migrations.CreateModel(
            name='OrderExtField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u503c')),
                ('originalOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Order', verbose_name='\u5355\u636e')),
                ('relatedBp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.BP', verbose_name='\u5173\u8054\u4f19\u4f34')),
                ('relatedOrder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatedOrder_set', to='crm.Order', verbose_name='\u5173\u8054\u5355\u636e')),
            ],
            options={
                'verbose_name': '\u5355\u636e\u6269\u5c55\u5b57\u6bb5\u8868',
                'verbose_name_plural': '\u5355\u636e\u6269\u5c55\u5b57\u6bb5\u8868',
            },
        ),
        migrations.CreateModel(
            name='OrderExtFieldType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=5, verbose_name='\u4e3b\u952e')),
                ('description', models.CharField(max_length=50, verbose_name='\u63cf\u8ff0')),
            ],
            options={
                'db_table': 'sales_OrderExtFieldType',
                'verbose_name': '\u5355\u636e\u6269\u5c55\u5b57\u6bb5\u7c7b\u578b\u8868',
                'verbose_name_plural': '\u5355\u636e\u6269\u5c55\u5b57\u6bb5\u7c7b\u578b\u8868',
            },
        ),
        migrations.CreateModel(
            name='OrderExtSelectionFieldType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldKey', models.CharField(max_length=5, verbose_name='\u5b57\u6bb5\u4e3b\u952e')),
                ('key', models.CharField(max_length=50, verbose_name='\u4e3b\u952e')),
                ('description', models.CharField(max_length=50, verbose_name='\u63cf\u8ff0')),
                ('sortOrder', models.IntegerField(blank=True, null=True, verbose_name='\u6392\u5e8f\u53f7')),
            ],
            options={
                'verbose_name': '\u5355\u636e\u9009\u9879\u5b57\u6bb5\u5b9a\u4e49',
                'verbose_name_plural': '\u5355\u636e\u9009\u9879\u5b57\u6bb5\u5b9a\u4e49',
            },
        ),
        migrations.CreateModel(
            name='OrderFieldDef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldKey', models.CharField(max_length=50, verbose_name='\u5b57\u6bb5\u4e3b\u952e')),
                ('attributeType', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u5b57\u6bb5\u5c5e\u6027')),
                ('valueType', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u503c\u7c7b\u578b')),
                ('storeType', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5b58\u50a8\u7c7b\u578b')),
                ('storeColumn', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5b58\u50a8\u5b57\u6bb5')),
                ('storeKey', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5b58\u50a8\u952e\u503c')),
                ('fieldType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.FieldType', verbose_name='\u5b57\u6bb5\u7c7b\u578b')),
            ],
            options={
                'verbose_name': '\u5355\u636e\u5b57\u6bb5\u5b9a\u4e49\u8868',
                'verbose_name_plural': '\u5355\u636e\u5b57\u6bb5\u5b9a\u4e49\u8868',
            },
        ),
        migrations.CreateModel(
            name='OrderFileAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u79f0')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u63cf\u8ff0')),
                ('actualfilename', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5b9e\u9645\u6587\u4ef6\u540d')),
                ('file', models.FileField(blank=True, null=True, upload_to=b'attachments', verbose_name='\u6587\u4ef6')),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'attachments', verbose_name='\u56fe\u7247')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u4e8e')),
                ('deleteFlag', models.BooleanField(default=False, verbose_name='\u5220\u9664\u6807\u8bb0')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fileCreator', to='crm.BP', verbose_name='\u521b\u5efa\u8005')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Order', verbose_name='\u5355\u636e')),
            ],
            options={
                'verbose_name': '\u5355\u636e\u6587\u4ef6\u9644\u4ef6',
                'verbose_name_plural': '\u5355\u636e\u6587\u4ef6\u9644\u4ef6',
            },
        ),
        migrations.CreateModel(
            name='OrderFollowUpDef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5907\u6ce8')),
                ('valid', models.BooleanField(default=True, verbose_name='\u6709\u6548\u6027')),
            ],
            options={
                'verbose_name': '\u5355\u636e\u8ddf\u8fdb\u7c7b\u578b\u5b9a\u4e49\u8868',
                'verbose_name_plural': '\u5355\u636e\u8ddf\u8fdb\u7c7b\u578b\u5b9a\u4e49\u8868',
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.IntegerField(verbose_name='\u5355\u636e\u7f16\u53f7')),
                ('orderField', models.CharField(max_length=50, verbose_name='\u5355\u636e\u5b57\u6bb5')),
                ('oldValue', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5b57\u6bb5\u65e7\u503c')),
                ('oldKeyValue', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5b57\u6bb5\u65e7\u952e\u503c')),
                ('newValue', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5b57\u6bb5\u65b0\u503c')),
                ('newKeyValue', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5b57\u6bb5\u65b0\u952e\u503c')),
                ('updatedBy', models.CharField(max_length=255, verbose_name='\u66f4\u65b0\u8005')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u4e8e')),
            ],
            options={
                'verbose_name': '\u5355\u636e\u5386\u53f2\u8bb0\u5f55\u8868\uff08\u5e9f\u9664\uff09',
                'verbose_name_plural': '\u5355\u636e\u5386\u53f2\u8bb0\u5f55\u8868\uff08\u5e9f\u9664\uff09',
            },
        ),
        migrations.CreateModel(
            name='OrderPF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.BooleanField(default=False, verbose_name='\u4e3b\u4f19\u4f34')),
                ('bp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.BP', verbose_name='\u5173\u8054\u5546\u4e1a\u4f19\u4f34')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Order', verbose_name='\u5355\u636e')),
            ],
            options={
                'verbose_name': '\u5355\u636e\u5546\u4e1a\u4f19\u4f34\u5173\u8054\u8868',
                'verbose_name_plural': '\u5355\u636e\u5546\u4e1a\u4f19\u4f34\u5173\u8054\u8868',
            },
        ),
        migrations.CreateModel(
            name='OrderRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5907\u6ce8')),
                ('valid', models.BooleanField(default=True, verbose_name='\u6709\u6548\u6027')),
                ('orderA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asOrderA', to='crm.Order', verbose_name='\u5355\u636eA')),
                ('orderB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asOrderB', to='crm.Order', verbose_name='\u5355\u636eB')),
            ],
            options={
                'verbose_name': '\u5355\u636e\u5173\u7cfb',
                'verbose_name_plural': '\u5355\u636e\u5173\u7cfb',
            },
        ),
        migrations.CreateModel(
            name='OrderRelType',
            fields=[
                ('key', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='\u4e3b\u952e')),
                ('description', models.CharField(max_length=255, verbose_name='\u63cf\u8ff0')),
                ('descAtoB', models.CharField(blank=True, max_length=255, null=True, verbose_name='A\u5bf9B\u5173\u7cfb\u540d\u79f0')),
                ('descBtoA', models.CharField(blank=True, max_length=255, null=True, verbose_name='B\u5bf9A\u5173\u7cfb\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u5355\u636e\u5173\u7cfb\u7c7b\u578b',
                'verbose_name_plural': '\u5355\u636e\u5173\u7cfb\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='OrderText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u4e8e')),
                ('content', models.TextField(blank=True, null=True, verbose_name='\u5185\u5bb9')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textCreator', to='crm.BP', verbose_name='\u521b\u5efa\u8005')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Order', verbose_name='\u5355\u636e')),
            ],
            options={
                'verbose_name': '\u5355\u636e\u6587\u672c\u8868',
                'verbose_name_plural': '\u5355\u636e\u6587\u672c\u8868',
            },
        ),
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('key', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='\u4e3b\u952e')),
                ('description', models.CharField(max_length=255, verbose_name='\u63cf\u8ff0')),
                ('assignmentBlock', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u6269\u5c55\u6846')),
                ('baseType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.OrderBaseType', verbose_name='\u57fa\u672c\u7c7b\u578b')),
            ],
            options={
                'verbose_name': '\u5355\u636e\u7c7b\u578b\u5b9a\u4e49',
                'verbose_name_plural': '\u5355\u636e\u7c7b\u578b\u5b9a\u4e49',
            },
        ),
        migrations.CreateModel(
            name='PFType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=5, verbose_name='\u4e3b\u952e')),
                ('description', models.CharField(max_length=255, verbose_name='\u63cf\u8ff0')),
                ('minimum', models.IntegerField(blank=True, null=True, verbose_name='\u6700\u5c0f\u51fa\u73b0\u6b21\u6570')),
                ('maximum', models.IntegerField(blank=True, null=True, verbose_name='\u6700\u5927\u51fa\u73b0\u6b21\u6570')),
                ('orderType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.OrderType', verbose_name='\u5355\u636e\u7c7b\u578b')),
            ],
            options={
                'db_table': 'sales_PFType',
                'verbose_name': '\u5408\u4f5c\u4f19\u4f34\u5173\u8054\u7c7b\u578b\u5b9a\u4e49',
                'verbose_name_plural': '\u5408\u4f5c\u4f19\u4f34\u5173\u8054\u7c7b\u578b\u5b9a\u4e49',
            },
        ),
        migrations.CreateModel(
            name='PriorityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=5, verbose_name='\u4e3b\u952e')),
                ('description', models.CharField(max_length=50, verbose_name='\u63cf\u8ff0')),
                ('sortOrder', models.IntegerField(blank=True, null=True, verbose_name='\u6392\u5e8f\u53f7')),
                ('orderType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.OrderType', verbose_name='\u5355\u636e\u7c7b\u578b')),
            ],
            options={
                'verbose_name': '\u4f18\u5148\u7ea7\u5b9a\u4e49',
                'verbose_name_plural': '\u4f18\u5148\u7ea7',
            },
        ),
        migrations.CreateModel(
            name='SiteAppType',
            fields=[
                ('appId', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='\u5e94\u7528\u4e3b\u952e')),
                ('description', models.CharField(max_length=50, verbose_name='\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u7f51\u7ad9\u5e94\u7528\u5b9a\u4e49\u8868',
                'verbose_name_plural': '\u7f51\u7ad9\u5e94\u7528\u5b9a\u4e49\u8868',
            },
        ),
        migrations.CreateModel(
            name='SiteLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=5, verbose_name='\u4e3b\u952e')),
                ('description', models.CharField(max_length=50, verbose_name='\u8bed\u8a00\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u7f51\u7ad9\u8bed\u8a00',
                'verbose_name_plural': '\u7f51\u7ad9\u8bed\u8a00',
            },
        ),
        migrations.CreateModel(
            name='SiteMenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phraseId', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u77ed\u8bed\u4e3b\u952e')),
                ('appId', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u77ed\u8bed\u5e94\u7528')),
                ('pageApp', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5e94\u7528')),
                ('sortOrder', models.IntegerField(verbose_name='\u6392\u5e8f\u53f7')),
                ('valid', models.BooleanField(default=True, verbose_name='\u6709\u6548\u6027')),
                ('parentMenuId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.SiteMenuItem', verbose_name='\u7236\u83dc\u5355\u7f16\u53f7')),
            ],
            options={
                'verbose_name': '\u7f51\u7ad9\u83dc\u5355\u5b9a\u4e49\u8868',
                'verbose_name_plural': '\u7f51\u7ad9\u83dc\u5355\u5b9a\u4e49\u8868',
            },
        ),
        migrations.CreateModel(
            name='SiteMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True, verbose_name='\u5185\u5bb9')),
                ('sentAt', models.DateTimeField(verbose_name='\u53d1\u9001\u65f6\u95f4')),
                ('receiverReadFlag', models.BooleanField(default=False, verbose_name='\u63a5\u6536\u8005\u5df2\u8bfb\u6807\u8bb0')),
                ('receiverDeleteFlag', models.BooleanField(default=False, verbose_name='\u63a5\u6536\u8005\u5220\u9664\u6807\u8bb0')),
                ('senderDeleteFlag', models.BooleanField(default=False, verbose_name='\u53d1\u9001\u8005\u5220\u9664\u6807\u8bb0')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u6d88\u606f\u8868',
                'verbose_name_plural': '\u7528\u6237\u6d88\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='SitePhrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phraseId', models.CharField(max_length=20, verbose_name='\u77ed\u8bed\u4e3b\u952e')),
                ('content', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5185\u5bb9')),
                ('bigContent', models.TextField(blank=True, null=True, verbose_name='\u5927\u6587\u672c\u5185\u5bb9')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.SiteAppType', verbose_name='\u5e94\u7528')),
                ('phraseLan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.SiteLanguage', verbose_name='\u8bed\u8a00')),
            ],
            options={
                'db_table': 'sales_SitePhrase',
                'verbose_name': '\u7f51\u7ad9\u77ed\u8bed\u56fd\u9645\u5316\u8868',
                'verbose_name_plural': '\u7f51\u7ad9\u77ed\u8bed\u56fd\u9645\u5316\u8868',
            },
        ),
        migrations.CreateModel(
            name='SLTAccountMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bpId', models.IntegerField(verbose_name='CRM\u4f01\u4e1a\uff08BP\uff09Id')),
                ('sltAccountNumber', models.CharField(max_length=255, verbose_name='\u5c71\u65c5\u901a\u8d26\u6237\uff08Account Number\uff09')),
                ('accountMemo', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u8d26\u6237\u5907\u6ce8')),
                ('agentBpId', models.IntegerField(blank=True, null=True, verbose_name='CRM\u4ee3\u7406\u5546\uff08BP\uff09Id')),
                ('sltAgentId', models.CharField(blank=True, max_length=255, null=True, verbose_name='TMC\u8d26\u6237\uff08Agent Id\uff09')),
                ('agentMemo', models.CharField(blank=True, max_length=255, null=True, verbose_name='TMC\u5907\u6ce8')),
                ('valid', models.BooleanField(default=True, verbose_name='\u6709\u6548\u6027')),
            ],
            options={
                'verbose_name': '\u5c71\u65c5\u901a\u8d26\u6237\u5173\u8054\u8868',
                'verbose_name_plural': '\u5c71\u65c5\u901a\u8d26\u6237\u5173\u8054\u8868',
            },
        ),
        migrations.CreateModel(
            name='StatusType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=5, verbose_name='\u4e3b\u952e')),
                ('description', models.CharField(max_length=50, verbose_name='\u63cf\u8ff0')),
                ('sortOrder', models.IntegerField(blank=True, null=True, verbose_name='\u6392\u5e8f\u53f7')),
                ('orderType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.OrderType', verbose_name='\u5355\u636e\u7c7b\u578b')),
            ],
            options={
                'verbose_name': '\u72b6\u6001\u5b9a\u4e49',
                'verbose_name_plural': '\u72b6\u6001\u5b9a\u4e49',
            },
        ),
        migrations.CreateModel(
            name='StdViewLayoutConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.BooleanField(verbose_name='\u662f\u5426\u53ef\u89c1')),
                ('required', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5fc5\u987b')),
                ('editable', models.BooleanField(default=True, verbose_name='\u53ef\u5426\u7f16\u8f91')),
                ('labelPhraseId', models.CharField(max_length=20, verbose_name='\u6807\u7b7e\u77ed\u8bed\u4e3b\u952e')),
                ('appId', models.CharField(max_length=20, verbose_name='\u77ed\u8bed\u5e94\u7528\u4e3b\u952e')),
                ('locRow', models.IntegerField(verbose_name='\u6240\u5728\u884c')),
                ('locCol', models.IntegerField(verbose_name='\u6240\u5728\u5217')),
                ('locWidth', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u5bbd\u5ea6')),
                ('locHeight', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u9ad8\u5ea6')),
                ('valid', models.BooleanField(default=True, verbose_name='\u6709\u6548\u6027')),
            ],
            options={
                'verbose_name': '\u5355\u636e\u6807\u51c6\u89c6\u56fe\u914d\u7f6e\u8868',
                'verbose_name_plural': '\u5355\u636e\u6807\u51c6\u89c6\u56fe\u914d\u7f6e\u8868',
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='\u4e3b\u952e')),
                ('property1', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u9644\u5c5e\u952e1')),
                ('property2', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u9644\u5c5e\u4ef62')),
                ('value1', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u503c1')),
                ('value2', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u503c2')),
            ],
            options={
                'verbose_name': '\u7cfb\u7edf\u914d\u7f6e\u8868',
                'verbose_name_plural': '\u7cfb\u7edf\u914d\u7f6e\u8868',
            },
        ),
        migrations.CreateModel(
            name='TextType',
            fields=[
                ('key', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='\u4e3b\u952e')),
                ('description', models.CharField(max_length=255, verbose_name='\u63cf\u8ff0')),
                ('orderType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.OrderType', verbose_name='\u5355\u636e\u7c7b\u578b')),
            ],
            options={
                'verbose_name': '\u6587\u672c\u7c7b\u578b\u5b9a\u4e49',
                'verbose_name_plural': '\u6587\u672c\u7c7b\u578b\u5b9a\u4e49',
            },
        ),
        migrations.CreateModel(
            name='UploadFilesTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageFile', models.ImageField(upload_to=b'uploads', verbose_name='\u56fe\u7247\u6587\u4ef6')),
                ('normalFile', models.FileField(upload_to=b'uploads', verbose_name='\u666e\u901a\u6587\u4ef6')),
            ],
            options={
                'verbose_name': '\u4e34\u65f6\u4e0a\u4f20\u6587\u4ef6',
                'verbose_name_plural': '\u4e34\u65f6\u4e0a\u4f20\u6587\u4ef6',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickName', models.CharField(max_length=50, verbose_name='\u6635\u79f0')),
                ('realName', models.CharField(max_length=50, verbose_name='\u59d3\u540d')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u4fe1\u606f',
                'verbose_name_plural': '\u7528\u6237\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u6807\u9898')),
                ('type', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7c7b\u578b')),
                ('text', models.TextField(blank=True, null=True, verbose_name='\u5185\u5bb9')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u53cd\u9988',
                'verbose_name_plural': '\u7528\u6237\u53cd\u9988',
            },
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(max_length=100, verbose_name='\u5bc6\u7801')),
                ('passwordEncrypted', models.BooleanField(default=False, verbose_name='\u5df2\u52a0\u5bc6')),
                ('failureCount', models.IntegerField(default=0, verbose_name='\u5931\u8d25\u6b21\u6570')),
                ('lastLoginAt', models.DateTimeField(blank=True, null=True, verbose_name='\u6700\u540e\u767b\u5f55\u65f6\u95f4')),
                ('pulseAt', models.DateTimeField(blank=True, null=True, verbose_name='\u6700\u540e\u5fc3\u8df3\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u767b\u5f55\u4fe1\u606f',
                'verbose_name_plural': '\u7528\u6237\u767b\u5f55\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='UserLoginStatus',
            fields=[
                ('key', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='\u4e3b\u952e')),
                ('description', models.CharField(max_length=255, verbose_name='\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u767b\u5f55\u72b6\u6001',
                'verbose_name_plural': '\u7528\u6237\u767b\u5f55\u72b6\u6001',
            },
        ),
        migrations.CreateModel(
            name='UserOrderViewHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.IntegerField(verbose_name='\u5355\u636e\u7f16\u53f7')),
                ('viewedAt', models.DateTimeField(auto_now=True, verbose_name='\u67e5\u770b\u65f6\u95f4')),
                ('userlogin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserLogin', verbose_name='\u7528\u6237\u767b\u5f55\u4fe1\u606f')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u5355\u636e\u67e5\u770b\u5386\u53f2\u8bb0\u5f55\u8868\uff08\u5e9f\u9664\uff09',
                'verbose_name_plural': '\u7528\u6237\u5355\u636e\u67e5\u770b\u5386\u53f2\u8bb0\u5f55\u8868\uff08\u5e9f\u9664\uff09',
            },
        ),
        migrations.CreateModel(
            name='UserParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u79f0')),
                ('value', models.CharField(max_length=50, verbose_name='\u503c')),
                ('userlogin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserLogin', verbose_name='\u7528\u6237\u767b\u5f55\u4fe1\u606f')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u53c2\u6570',
                'verbose_name_plural': '\u7528\u6237\u53c2\u6570',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.BooleanField(default=True, verbose_name='\u6709\u6548\u6027')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u914d\u7f6e\u6587\u4ef6',
                'verbose_name_plural': '\u7528\u6237\u914d\u7f6e\u6587\u4ef6',
            },
        ),
        migrations.CreateModel(
            name='UserProfileAuthObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.BooleanField(default=True, verbose_name='\u6709\u6548\u6027')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u914d\u7f6e\u6587\u4ef6\u5bf9\u5e94\u6743\u9650\u5bf9\u8c61',
                'verbose_name_plural': '\u7528\u6237\u914d\u7f6e\u6587\u4ef6\u5bf9\u5e94\u6743\u9650\u5bf9\u8c61',
            },
        ),
        migrations.CreateModel(
            name='UserProfileType',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='\u4e3b\u952e')),
                ('description', models.CharField(max_length=255, verbose_name='\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u914d\u7f6e\u6587\u4ef6\u7c7b\u578b',
                'verbose_name_plural': '\u7528\u6237\u914d\u7f6e\u6587\u4ef6\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.BooleanField(default=True, verbose_name='\u6709\u6548\u6027')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u89d2\u8272',
                'verbose_name_plural': '\u7528\u6237\u89d2\u8272',
            },
        ),
        migrations.CreateModel(
            name='UserRoleType',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='\u4e3b\u952e')),
                ('description', models.CharField(max_length=255, verbose_name='\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u89d2\u8272\u7c7b\u578b',
                'verbose_name_plural': '\u7528\u6237\u89d2\u8272\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='UserSavedSearchFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='\u7c7b\u578b')),
                ('name', models.CharField(max_length=255, verbose_name='\u5b58\u50a8\u540d\u79f0')),
                ('sortOrder', models.IntegerField(verbose_name='\u6392\u5e8f\u53f7')),
                ('property', models.CharField(max_length=255, verbose_name='\u5b57\u6bb5')),
                ('operation', models.CharField(max_length=255, verbose_name='\u64cd\u4f5c\u7b26')),
                ('low', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u4f4e\u7aef\u503c')),
                ('high', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u9ad8\u7aef\u503c')),
                ('userlogin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserLogin', verbose_name='\u7528\u6237\u767b\u5f55\u4fe1\u606f')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u641c\u7d22\u5b57\u6bb5\u4fdd\u5b58\u8868',
                'verbose_name_plural': '\u7528\u6237\u641c\u7d22\u5b57\u6bb5\u4fdd\u5b58\u8868',
            },
        ),
        migrations.CreateModel(
            name='UserSingleAuthObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.BooleanField(default=True, verbose_name='\u6709\u6548\u6027')),
                ('singleAuthObject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.AuthObject', verbose_name='\u6743\u9650\u5bf9\u8c61\u7c7b\u578b')),
                ('userlogin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserLogin', verbose_name='\u7528\u6237\u767b\u5f55\u4fe1\u606f')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u6743\u9650\u5bf9\u8c61',
                'verbose_name_plural': '\u7528\u6237\u6743\u9650\u5bf9\u8c61',
            },
        ),
        migrations.CreateModel(
            name='UserViewHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectId', models.IntegerField(verbose_name='\u5b9e\u4f53\u7f16\u53f7')),
                ('type', models.CharField(max_length=20, verbose_name='\u7c7b\u578b')),
                ('viewedAt', models.DateTimeField(verbose_name='\u67e5\u770b\u65f6\u95f4')),
                ('userlogin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserLogin', verbose_name='\u7528\u6237\u767b\u5f55\u4fe1\u606f')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u5355\u636e\u67e5\u770b\u5386\u53f2\u8bb0\u5f55\u8868',
                'verbose_name_plural': '\u7528\u6237\u5355\u636e\u67e5\u770b\u5386\u53f2\u8bb0\u5f55\u8868',
            },
        ),
        migrations.CreateModel(
            name='ViewType',
            fields=[
                ('key', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='\u4e3b\u952e')),
                ('description', models.CharField(max_length=255, verbose_name='\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u89c6\u56fe\u7c7b\u578b\u5b9a\u4e49\u8868',
                'verbose_name_plural': '\u89c6\u56fe\u7c7b\u578b\u5b9a\u4e49\u8868',
            },
        ),
        migrations.AddField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserRoleType', verbose_name='\u7528\u6237\u89d2\u8272\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='userlogin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserLogin', verbose_name='\u7528\u6237\u767b\u5f55\u4fe1\u606f'),
        ),
        migrations.AddField(
            model_name='userprofileauthobject',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserProfileType', verbose_name='\u7528\u6237\u914d\u7f6e\u6587\u4ef6'),
        ),
        migrations.AddField(
            model_name='userprofileauthobject',
            name='singleAuthObject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.AuthObject', verbose_name='\u6743\u9650\u5bf9\u8c61\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserProfileType', verbose_name='\u7528\u6237\u914d\u7f6e\u6587\u4ef6\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='userlogin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserLogin', verbose_name='\u7528\u6237\u767b\u5f55\u4fe1\u606f'),
        ),
        migrations.AddField(
            model_name='userlogin',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.UserLoginStatus', verbose_name='\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='userlogin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crm.User', verbose_name='\u7528\u6237\u4fe1\u606f\u5b9e\u4f53'),
        ),
        migrations.AddField(
            model_name='userlogin',
            name='userbp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.BP', verbose_name='\u7528\u6237\u5b9e\u4f53'),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='userLogin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserLogin', verbose_name='\u7528\u6237\u767b\u5f55\u4fe1\u606f'),
        ),
        migrations.AddField(
            model_name='stdviewlayoutconf',
            name='businessRole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.UserRoleType', verbose_name='\u4e1a\u52a1\u89d2\u8272'),
        ),
        migrations.AddField(
            model_name='stdviewlayoutconf',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.OrderFieldDef', verbose_name='\u5b57\u6bb5\u5b9a\u4e49'),
        ),
        migrations.AddField(
            model_name='stdviewlayoutconf',
            name='viewType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.ViewType', verbose_name='\u89c6\u56fe\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='sitemessage',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asMessageReceiver', to='crm.UserLogin', verbose_name='\u63a5\u6536\u8005'),
        ),
        migrations.AddField(
            model_name='sitemessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asMessageSender', to='crm.UserLogin', verbose_name='\u53d1\u9001\u8005'),
        ),
        migrations.AddField(
            model_name='sitemenuitem',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserRoleType', verbose_name='\u7528\u6237\u89d2\u8272\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='ordertext',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.TextType', verbose_name='\u6587\u672c\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='orderrelation',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.OrderRelType', verbose_name='\u5355\u636e\u5173\u7cfb\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='orderpf',
            name='pf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.PFType', verbose_name='\u5173\u8054\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='orderpf',
            name='relatedOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asRelatedOrder', to='crm.Order', verbose_name='\u5173\u8054\u5355\u636e'),
        ),
        migrations.AddField(
            model_name='orderfollowupdef',
            name='orderTypeA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asFollowUpTypeA', to='crm.OrderType', verbose_name='\u5355\u636e\u7c7b\u578bA'),
        ),
        migrations.AddField(
            model_name='orderfollowupdef',
            name='orderTypeB',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asFollowUpTypeB', to='crm.OrderType', verbose_name='\u5355\u636e\u7c7b\u578bB'),
        ),
        migrations.AddField(
            model_name='orderfollowupdef',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.OrderRelType', verbose_name='\u5173\u7cfb\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='orderfielddef',
            name='orderType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.OrderType', verbose_name='\u5355\u636e\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='orderextselectionfieldtype',
            name='orderType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.OrderType', verbose_name='\u5355\u636e\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='orderextfieldtype',
            name='orderType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.OrderType', verbose_name='\u5355\u636e\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='orderextfield',
            name='relatedSelection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.OrderExtSelectionFieldType', verbose_name='\u5173\u8054\u9009\u9879'),
        ),
        migrations.AddField(
            model_name='orderextfield',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.OrderExtFieldType', verbose_name='\u6269\u5c55\u5b57\u6bb5\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='orderbedef',
            name='orderType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.OrderType', verbose_name='\u5355\u636e\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='order',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.PriorityType', verbose_name='\u4f18\u5148\u7ea7'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.StatusType', verbose_name='\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.OrderType', verbose_name='\u5355\u636e\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='order',
            name='updatedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updater', to='crm.BP', verbose_name='\u66f4\u65b0\u8005'),
        ),
        migrations.AddField(
            model_name='bptexttype',
            name='bpType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.BPType', verbose_name='\u4f19\u4f34\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='bptext',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.BPTextType', verbose_name='\u6587\u672c\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='bpstdviewlayoutconf',
            name='businessRole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.UserRoleType', verbose_name='\u4e1a\u52a1\u89d2\u8272'),
        ),
        migrations.AddField(
            model_name='bpstdviewlayoutconf',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.BPFieldDef', verbose_name='\u5b57\u6bb5\u5b9a\u4e49'),
        ),
        migrations.AddField(
            model_name='bpstdviewlayoutconf',
            name='viewType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.ViewType', verbose_name='\u89c6\u56fe\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='bprelation',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.BPRelType', verbose_name='\u4f19\u4f34\u5173\u7cfb\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='bpfielddef',
            name='bpType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.BPType', verbose_name='\u4f19\u4f34\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='bpfielddef',
            name='fieldType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.FieldType', verbose_name='\u5b57\u6bb5\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='bpbedef',
            name='bpType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.BPType', verbose_name='\u4f19\u4f34\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='bp',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.BPType', verbose_name='\u4f19\u4f34\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='authobject',
            name='authObject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.AuthObjectType', verbose_name='\u6743\u9650\u5bf9\u8c61\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='appnavaccess',
            name='userLogin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserLogin', verbose_name='\u7528\u6237\u767b\u5f55\u4fe1\u606f'),
        ),
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.DistrictType', verbose_name='\u5730\u533a\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='address',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.AddressType', verbose_name='\u5730\u5740\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='activity',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crm.Order', verbose_name='\u5355\u636e'),
        ),
        migrations.AlterUniqueTogether(
            name='sitephrase',
            unique_together=set([('phraseId', 'app', 'phraseLan')]),
        ),
        migrations.AlterUniqueTogether(
            name='pftype',
            unique_together=set([('orderType', 'key')]),
        ),
        migrations.AlterUniqueTogether(
            name='orderextfieldtype',
            unique_together=set([('orderType', 'key')]),
        ),
    ]
